In [2]:
import numpy as np

prob = np.array([[1.0,0.0,0.0], [0.0,0.0,1.0], [0.0,1.0,0.0]])

print(prob)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [4]:
from numpy import asarray
from numpy import expand_dims
from numpy import log
from numpy import mean
from numpy import exp
 
# calculate the inception score for p(y|x)
def calculate_inception_score(p_yx, eps=1E-16):
 # calculate p(y)
 p_y = expand_dims(p_yx.mean(axis=0), 0)
 # kl divergence for each image
 kl_d = p_yx * (log(p_yx + eps) - log(p_y + eps))
 # sum over classes
 sum_kl_d = kl_d.sum(axis=1)
 # average over images
 avg_kl_d = mean(sum_kl_d)
 # undo the logs
 is_score = exp(avg_kl_d)
 return is_score

In [5]:
calculate_inception_score(prob)

2.999999999999999